/*
 * File: app/view/Panel/Footer.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SMS.view.Panel.Footer', {
	extend: 'Ext.container.Container',
	alias: 'widget.panel.footer',

	requires: [
		'SMS.view.Panel.FooterViewModel',
		'Ext.container.Container',
		'Ext.button.Button',
		'Ext.form.Label'
	],

	viewModel: {
		type: 'panel.footer'
	},
	cls: 'sms-desktop-section-footer ',
	height: 60,

	layout: {
		type: 'hbox',
		align: 'middle',
		pack: 'center'
	},
	items: [
		{
			xtype: 'container',
			cls: 'sms-desktop-section-footer-share ',
			margin: '0 0 0 10',
			padding: 10,
			width: 100,
			layout: {
				type: 'hbox',
				align: 'stretch'
			},
			items: [
				{
					xtype: 'button',
					flex: 1,
					cls: 'sms-icon-btn',
					style: {
						'background-image': 'url(\'resources/images_classic/site/DesktopFooterIconFacebook.png\')'
					},
					href: 'https://www.facebook.com/LOCSoftware'
				},
				{
					xtype: 'button',
					flex: 1,
					cls: 'sms-icon-btn',
					style: {
						'background-image': 'url(\'resources/images_classic/site/DesktopFooterIconLinkedIn.png\')'
					},
					href: 'https://www.linkedin.com/company/loc-software/'
				},
				{
					xtype: 'button',
					flex: 1,
					cls: 'sms-icon-btn',
					height: 30,
					hidden: true,
					style: {
						'background-image': 'url(\'resources/images_classic/site/DesktopFooterIconTwitter.png\')'
					}
				},
				{
					xtype: 'button',
					flex: 1,
					cls: 'sms-icon-btn',
					height: 30,
					hidden: true,
					style: {
						'background-image': 'url(\'resources/images_classic/site/DesktopFooterIconGoogle.png\')'
					}
				}
			]
		},
		{
			xtype: 'container',
			flex: 2,
			layout: {
				type: 'vbox',
				align: 'center'
			},
			items: [
				{
					xtype: 'label',
					text: 'Copyright ©‎ LOC Software 2018'
				}
			]
		},
		{
			xtype: 'container',
			margin: '0 15 0 0',
			items: [
				{
					xtype: 'button',
					border: 0,
					cls: 'sms-icon-btn',
					height: 45,
					width: 100,
					href: 'https://itunes.apple.com/us/app/loc-software-mstore/id736888808?ls=1&mt=8',
					icon: 'resources/images_classic/site/DesktopFooterButtonAppStore.png',
					iconAlign: 'top',
					scale: 'large'
				},
				{
					xtype: 'button',
					border: 0,
					cls: 'sms-icon-btn',
					height: 45,
					width: 100,
					href: 'https://play.google.com/store/apps/details?id=com.locsoftware.mStore450',
					icon: 'resources/images_classic/site/DesktopFooterButtonPlay.png',
					iconAlign: 'top',
					scale: 'large'
				}
			]
		}
	]

});